-- Add more dummy questions for testing
INSERT INTO public.questions (title, description, author_id, tags, vote_count, answer_count, view_count) VALUES 
('How to implement state management in React?', 'I am building a large React application and struggling with state management. What are the best practices for managing state across multiple components? Should I use Context API, Redux, or Zustand?', (SELECT user_id FROM public.profiles WHERE username = 'DevGuru' LIMIT 1), ARRAY['react', 'state-management', 'redux'], 15, 3, 89),
('TypeScript generics best practices', 'I am learning TypeScript and having trouble understanding generics. Can someone explain when and how to use generics effectively? I would appreciate some practical examples.', (SELECT user_id FROM public.profiles WHERE username = 'TechWizard' LIMIT 1), ARRAY['typescript', 'generics', 'types'], 12, 2, 67),
('CSS Grid vs Flexbox - When to use which?', 'I keep getting confused about when to use CSS Grid vs Flexbox. What are the specific use cases for each? Can someone provide a clear comparison with examples?', (SELECT user_id FROM public.profiles WHERE username = 'CSSMaster' LIMIT 1), ARRAY['css', 'grid', 'flexbox'], 8, 4, 45),
('Node.js authentication with JWT', 'I need to implement JWT authentication in my Node.js application. What is the best approach? How do I handle token refresh and security best practices?', (SELECT user_id FROM public.profiles WHERE username = 'FullStackDev' LIMIT 1), ARRAY['nodejs', 'jwt', 'authentication'], 20, 5, 156),
('React hooks dependency array confusion', 'I am constantly running into issues with React hooks dependency arrays. When should I include variables in the dependency array? What are the consequences of missing dependencies?', (SELECT user_id FROM public.profiles WHERE username = 'ReactNinja' LIMIT 1), ARRAY['react', 'hooks', 'useeffect'], 18, 6, 134),
('Database indexing strategies', 'My application is getting slow as the database grows. What are the best strategies for database indexing? How do I identify which columns need indexes?', (SELECT user_id FROM public.profiles WHERE username = 'CodeMaster' LIMIT 1), ARRAY['database', 'indexing', 'performance'], 14, 3, 78),
('Git branching strategies for teams', 'Our team is struggling with Git workflow. What are the best branching strategies for a team of 5 developers? Should we use GitFlow, GitHub Flow, or something else?', (SELECT user_id FROM public.profiles WHERE username = 'JSExpert' LIMIT 1), ARRAY['git', 'workflow', 'branching'], 10, 2, 92),
('API rate limiting implementation', 'How do I implement rate limiting for my REST API? What are the different strategies and which one should I choose for a medium-scale application?', (SELECT user_id FROM public.profiles WHERE username = 'TypeScriptPro' LIMIT 1), ARRAY['api', 'rate-limiting', 'rest'], 16, 4, 112),
('Responsive design breakpoints strategy', 'What is the best approach for choosing breakpoints in responsive design? How many breakpoints should I use and what screen sizes should I target?', (SELECT user_id FROM public.profiles WHERE username = 'CSSMaster' LIMIT 1), ARRAY['css', 'responsive', 'breakpoints'], 9, 3, 67),
('Testing strategies for React components', 'I want to improve my testing game for React components. What is the difference between unit tests, integration tests, and e2e tests? Which testing library should I use?', (SELECT user_id FROM public.profiles WHERE username = 'ReactNinja' LIMIT 1), ARRAY['react', 'testing', 'jest'], 13, 5, 88);